input:
  generate:
    interval: 2ms
    mapping: root = {}
  processors:
    - label: "get_a"
      cache:
        resource: file_cache
        operator: get
        key: cache
    - catch:
        - mapping: |
            root = {}
pipeline:
  processors:
    - label: "update_a"
      mapping: |
        root = if (this == null) { {} } else { this }
        root.a = if (this.a == null) {
          1
        } else { 
          this.a + 1
        }
    - label: "set_cache_a"
      cache:
        resource: file_cache
        operator: set
        key: cache
        value: '${! this }'
cache_resources:
  - label: file_cache
    file:
      directory: ./